### ISSUE TITLE
大佬，安装后怎么查看程序运行日志呢

### ISSUE THREAD

**Issue by liuyuan159** [zimoyin/Autojsx.WIFI#1]
大佬，安装后怎么查看程序运行日志呢

**Comment by zimoyin** [comment]
检查IDEA下方，控制台位置是否存在 Autojsx 控制台

**Comment by zimoyin** [comment]
&nbsp;非常荣幸您使用我的插件，在使用插件时候的遇到的问题，bug，想要的功能都可以和我分享一下，目前插件开发时运行环境为IDEA 社区版 旧UI，这也许将会在未来对新UI进行更好的支持。
&nbsp;您的建议对当前的开发是非常有帮助的，请在github或者通过邮箱留言。
