### ISSUE TITLE
是不是缺文件了，编译失败，或者能不能搞个能设置服务器IP的选项

### ISSUE THREAD

**Issue by qauzy** [zimoyin/Autojsx.WIFI#2]
我电脑有多个IP，其中有虚拟机的网桥IP是不能对外连接，但是插件硬是选择了这个IP来监听，然后找了你的源码来编译，发现编译不通过，看起来是缺了文件

**Comment by zimoyin** [comment]
1.  插件服务器监听IP 和 控制台 **显示的IP的地址是两套实现**，请检查物理机IP与端口是否正常的被插件服务器监听。
2.  github 上确实缺少必要类文件
感谢反馈

**Comment by qauzy** [comment]
是我autojs的问题，需要用readme提供的那个autojsx就正常了
