### ISSUE TITLE
能支持IDE打包么

### ISSUE THREAD

**Issue by RFSN** [zimoyin/Autojsx.WIFI#3]
开源大佬好，
能支持脱离手机环境打包APP吗，谢谢。

**Comment by zimoyin** [comment]
非常抱歉

Autox 新版本打包有BUG，我没有参考对象，所以这个建议不会采纳。

另外我对安卓知识约等于0，对IDE 打包APK来说是困难的。

或许以后会实现，但那是很久了

**Comment by zimoyin** [comment]
打包功能已经开发完成了，但是由于体积过大，不会和插件进行合并。他会单独的在一个GITHUb存储库中。按需要IDEA 插件会自行下载
这个问题到此结束了

**Comment by RFSN** [comment]
辛苦大佬了，有空学习一下，谢谢大佬。

**Comment by RFSN** [comment]
在您的仓库里面没有找到对应的项目，能给下地址吗，谢谢。

**Comment by zimoyin** [comment]
会在近期提交的，最长三天

**Comment by RFSN** [comment]
已看到您提交的打包项目了，谢谢大佬的辛苦付出。
万分感谢。
